services:
    webserver:
        build:
            context: .
            args:
                INT_PORT: ${INT_PORT}
        image: ${IMG_NAME}:latest
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEM}
        container_name: ${CONT_NAME}
        volumes:
            - "${WEB_ROOT}:/var/www"
        ports:
            - "${EXT_PORT}:${INT_PORT}"
        restart: unless-stopped
        environment:
           - TZ=${TZ} 
